### ISSUE TITLE
jsoncpp include dir bad path

### ISSUE THREAD

**Issue by kuboosoft** [UnitedRPMs/kodi-pvr-addons#2]
Well the log; I reported it in [bugzilla](https://bugzilla.redhat.com//show_bug.cgi?id=1336082)

```
+ pushd /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/build
~/build/BUILD/kodi-pvr-addons/pvr.argustv/build ~/build/BUILD/kodi-pvr-addons
+ export PKG_CONFIG_PATH=/builddir/build/SOURCES:/usr/lib64/pkgconfig
+ PKG_CONFIG_PATH=/builddir/build/SOURCES:/usr/lib64/pkgconfig
+ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib64/kodi ..
-- The C compiler identification is GNU 6.0.0
-- The CXX compiler identification is GNU 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking to see if CXX compiler accepts flag -flto
-- Checking to see if CXX compiler accepts flag -flto - yes
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.2
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find JsonCpp (missing: JSONCPP_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  FindJsonCpp.cmake:13 (find_package_handle_standard_args)
  CMakeLists.txt:71 (find_package)
-- Configuring incomplete, errors occurred!
See also "/builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/build/CMakeFiles/CMakeOutput.log".
error: Bad exit status from /var/tmp/rpm-tmp.POACdQ (%build)
    Bad exit status from /var/tmp/rpm-tmp.POACdQ (%build)
RPM build errors:
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 88, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/util.py", line 547, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/kodi-pvr-addons.spec
```

**Comment by kuboosoft** [comment]
Well with  the correct path, appear other problem:

```

+ mkdir -p pvr.argustv/build/
+ pushd /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/build
+ export PKG_CONFIG_PATH=/builddir/build/SOURCES:/usr/lib64/pkgconfig
+ PKG_CONFIG_PATH=/builddir/build/SOURCES:/usr/lib64/pkgconfig
+ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib64/kodi ..
~/build/BUILD/kodi-pvr-addons/pvr.argustv/build ~/build/BUILD/kodi-pvr-addons
-- The C compiler identification is GNU 6.0.0
-- The CXX compiler identification is GNU 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking to see if CXX compiler accepts flag -flto
-- Checking to see if CXX compiler accepts flag -flto - yes
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.2
-- Found JsonCpp: jsoncpp  
-- ARGUSTV_VERSION=1.11.13
-- Configuring done
-- Generating done
-- Build files have been written to: /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/build
+ make
Scanning dependencies of target tsreader
[  5%] Building CXX object src/lib/tsreader/CMakeFiles/tsreader.dir/FileReader.cpp.o
In file included from /usr/include/c++/6.0.0/x86_64-redhat-linux/bits/c++config.h:2385:0,
                 from /usr/include/c++/6.0.0/string:38,
                 from /usr/include/json/config.h:9,
                 from /usr/include/json/forwards.h:10,
                 from /usr/include/json/features.h:10,
                 from /usr/include/unistd.h:25,
                 from /usr/include/p8-platform/posix/os-types.h:35,
                 from /usr/include/p8-platform/os.h:37,
                 from /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/src/lib/tsreader/FileReader.h:36,
                 from /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/src/lib/tsreader/FileReader.cpp:35:
/usr/include/c++/6.0.0/x86_64-redhat-linux/bits/os_defines.h:44:19: error: missing binary operator before token "("
 #if __GLIBC_PREREQ(2,15) && defined(_GNU_SOURCE)
                   ^
In file included from /usr/include/c++/6.0.0/cwchar:44:0,
                 from /usr/include/c++/6.0.0/bits/postypes.h:40,
                 from /usr/include/c++/6.0.0/bits/char_traits.h:40,
                 from /usr/include/c++/6.0.0/string:40,
                 from /usr/include/json/config.h:9,
                 from /usr/include/json/forwards.h:10,
                 from /usr/include/json/features.h:10,
                 from /usr/include/unistd.h:25,
                 from /usr/include/p8-platform/posix/os-types.h:35,
                 from /usr/include/p8-platform/os.h:37,
                 from /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/src/lib/tsreader/FileReader.h:36,
                 from /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/src/lib/tsreader/FileReader.cpp:35:
/usr/include/wchar.h:74:43: error: missing binary operator before token "("
 # if defined __cplusplus && __GNUC_PREREQ (4, 4)
                                           ^
In file included from /usr/include/sched.h:43:0,
                 from /usr/include/pthread.h:23,
                 from /usr/include/c++/6.0.0/x86_64-redhat-linux/bits/gthr-default.h:35,
                 from /usr/include/c++/6.0.0/x86_64-redhat-linux/bits/gthr.h:148,
                 from /usr/include/c++/6.0.0/ext/atomicity.h:35,
                 from /usr/include/c++/6.0.0/bits/basic_string.h:39,
                 from /usr/include/c++/6.0.0/string:52,
                 from /usr/include/json/config.h:9,
                 from /usr/include/json/forwards.h:10,
                 from /usr/include/json/features.h:10,
                 from /usr/include/unistd.h:25,
                 from /usr/include/p8-platform/posix/os-types.h:35,
                 from /usr/include/p8-platform/os.h:37,
                 from /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/src/lib/tsreader/FileReader.h:36,
                 from /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/src/lib/tsreader/FileReader.cpp:35:
/usr/include/bits/sched.h:131:20: error: missing binary operator before token "("
 # if __GNUC_PREREQ (2, 91)
                    ^
/usr/include/bits/sched.h:169:20: error: missing binary operator before token "("
 # if __GNUC_PREREQ (2, 91)
                    ^
In file included from /usr/include/libio.h:56:0,
                 from /usr/include/stdio.h:74,
                 from /usr/include/c++/6.0.0/cstdio:42,
                 from /usr/include/c++/6.0.0/ext/string_conversions.h:43,
                 from /usr/include/c++/6.0.0/bits/basic_string.h:5402,
                 from /usr/include/c++/6.0.0/string:52,
                 from /usr/include/json/config.h:9,
                 from /usr/include/json/forwards.h:10,
                 from /usr/include/json/features.h:10,
                 from /usr/include/unistd.h:25,
                 from /usr/include/p8-platform/posix/os-types.h:35,
                 from /usr/include/p8-platform/os.h:37,
                 from /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/src/lib/tsreader/FileReader.h:36,
                 from /builddir/build/BUILD/kodi-pvr-addons/pvr.argustv/src/lib/tsreader/FileReader.cpp:35:
/usr/include/sys/cdefs.h:41:20: error: missing binary operator before token "("
 # if __GNUC_PREREQ (4, 6) && !defined _LIBC
                    ^
/usr/include/sys/cdefs.h:54:44: error: missing binary operator before token "("
 # if !defined __cplusplus && __GNUC_PREREQ (3, 3)
                                            ^
/usr/include/sys/cdefs.h:59:44: error: missing binary operator before token "("
 #  if defined __cplusplus && __GNUC_PREREQ (2,8)
                                            ^
/usr/include/sys/cdefs.h:135:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (4,3)
                   ^
/usr/include/sys/cdefs.h:148:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (2,97)
                   ^
/usr/include/sys/cdefs.h:210:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (2,96)
                   ^
/usr/include/sys/cdefs.h:218:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (4, 3)
                   ^
/usr/include/sys/cdefs.h:228:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (2,96)
                   ^
/usr/include/sys/cdefs.h:235:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (2,5)
                   ^
/usr/include/sys/cdefs.h:244:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (3,1)
                   ^
/usr/include/sys/cdefs.h:253:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (3,2)
                   ^
/usr/include/sys/cdefs.h:265:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (2,8)
                   ^
/usr/include/sys/cdefs.h:275:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (2,97)
                   ^
/usr/include/sys/cdefs.h:284:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (3,3)
                   ^
/usr/include/sys/cdefs.h:292:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (3,4)
                   ^
/usr/include/sys/cdefs.h:306:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (3,2)
                   ^
/usr/include/sys/cdefs.h:314:19: error: missing binary operator before token "("
 #if __GNUC_PREREQ (4,3)
```
